# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a55
TARGET_CPU_SMP := true
# 2nd Architecture
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-2a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a55

# AVB
BOARD_AVB_ENABLE := true

# Parmeters.txt
BOARD_BUILD_PARMETERS_TXT := true

# Bootloader
UBOOT_DIR :=../u-boot_android-mainline/u-boot/build
PRODUCT_COPY_FILES += \
    $(UBOOT_DIR)/idbloader.img:idbloader.img \
    $(UBOOT_DIR)/u-boot.itb:u-boot.itb

# Boot image
# https://source.android.com/docs/core/architecture/bootloader/partitions/generic-boot?hl=zh-cn#board-configurations
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864 # 64 MiB
KERNEL_DIR := ../kernel_android-15-6.6/out/orangepi3b/dist
TARGET_NO_KERNEL := true
BOARD_PREBUILT_BOOTIMAGE:= $(KERNEL_DIR)/boot.img
BOARD_BOOT_HEADER_VERSION := 4
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_INIT_BOOT_HEADER_VERSION := 4
BOARD_MKBOOTIMG_INIT_ARGS += --header_version $(BOARD_INIT_BOOT_HEADER_VERSION)

# Vendor boot image
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864 # 64 MiB
BOARD_USES_GENERIC_KERNEL_IMAGE := true
BOARD_MOVE_GSI_AVB_KEYS_TO_VENDOR_BOOT := true
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
# Modules
KERNEL_MODULES_DIR := $(KERNEL_DIR)
KERNEL_MODULES_KOS := $(wildcard $(KERNEL_MODULES_DIR)/*.ko)
KERNEL_MODULES_LOAD := $(strip $(shell cat $(firstword $(wildcard $(KERNEL_MODULES_DIR)/modules.load))))
BOARD_VENDOR_RAMDISK_KERNEL_MODULES := $(KERNEL_MODULES_KOS)
BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD := $(KERNEL_MODULES_LOAD)
# Dtb
DTB_DIR := $(KERNEL_DIR)
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_PREBUILT_DTBIMAGE_DIR := $(DTB_DIR)

# DTBO image
DTBO_DIR := $(KERNEL_DIR)
BOARD_PREBUILT_DTBO := \
    $(DTBO_DIR)/rk3566-orangepi-3b.dtb
BOARD_DTBOIMG_PARTITION_SIZE := 4194304 # 4 MiB
BOARD_DTBO_UNSIGNED := dtbo-unsigned.img
BOARD_PREBUILT_DTBOIMAGE = $(PRODUCT_OUT)/$(BOARD_DTBO_UNSIGNED)

# System image
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4

# Vendor image
TARGET_COPY_OUT_VENDOR := vendor
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4

# Product image
TARGET_COPY_OUT_PRODUCT := product
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4

# Cache image
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_CACHEIMAGE_PARTITION_SIZE := 1073741824 # 1 GiB

# Userdata image
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_USERDATAIMAGE_PARTITION_SIZE := 21474836480 # 20 GiB

# Super image
BOARD_BUILD_SUPER_IMAGE_BY_DEFAULT := true
BOARD_SUPER_PARTITION_SIZE := 3229614080 # 3072 + 8 MiB
BOARD_SUPER_PARTITION_GROUPS := default_dynamic_partitions
BOARD_DEFAULT_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor product
BOARD_DEFAULT_DYNAMIC_PARTITIONS_SIZE := 1610612736  # 1536 MiB, must less than BOARD_SUPER_PARTITION_SIZE / 2